### ISSUE TITLE
Possible naming problem

### ISSUE THREAD

**Issue by danlozano** [olddonkey/ODUIThreadGuard#1]
Hi, nice library.

Not really sure if this is a problem, that's why I did not do the pull request.

But, shouldn't your own swizzled methods, call the original implementations (and not itself) ?

```swift
func guardSetNeedsLayout() {
        checkThread()
        guardSetNeedsLayout() <----
    }

    func guardSetNeedsDisplay() {
        checkThread()
        guardSetNeedsDisplay() <----
    }

    func guardSetNeedsDisplayInRect(_ rect: CGRect) {
        checkThread()
        guardSetNeedsDisplayInRect(rect) <-----
    }
```

**Comment by lucianboboc** [comment]
I asked myself the same thing, isn't this an endless recursion? But it is not because implementations were swapped.
When setNeedsDisplay is called, the guardSetNeedsDisplay's body is executed. Also in the guardSetNeedsDisplay's body when it calls guardSetNeedsDisplay it actually calls the setNeedsDisplay because the implementation was swapped, so no recursion occurs :)

**Comment by danlozano** [comment]
Wow, confusing, but makes sense! haha

👍 thanks
